package com.replymate.core.reasoning

import com.replymate.core.conversation.MemoryContext

interface ConversationAnalyzer { fun analyze(message: String, hasHistory: Boolean): ConversationAnalysis }
class HeuristicConversationAnalyzer : ConversationAnalyzer {
    override fun analyze(message: String, hasHistory: Boolean): ConversationAnalysis { val lower = message.lowercase(); return ConversationAnalysis(message.take(80), if (listOf("urgent", "asap", "today").any(lower::contains)) 80 else 20, if (message.length > 240) 65 else 25, '?' in message || listOf("can you", "could you", "what", "why", "how").any(lower::contains), listOf("please", "can you", "could you", "help").any(lower::contains), listOf("hi", "hello", "hey").any { lower.startsWith(it) }, listOf("bye", "goodnight", "talk later").any(lower::contains), hasHistory && listOf("also", "and", "that", "it").any { lower.startsWith(it) }, listOf("lol", "haha", "😂").any(lower::contains), listOf("yeah right", "sure...", "/s").any(lower::contains), hasHistory) }
}
interface IntentDetector { fun detect(message: String, analysis: ConversationAnalysis): List<LabelConfidence<DetectedIntent>> }
class HeuristicIntentDetector : IntentDetector { override fun detect(message: String, analysis: ConversationAnalysis): List<LabelConfidence<DetectedIntent>> { val l=message.lowercase(); return buildList { if(analysis.hasQuestion)add(LabelConfidence(DetectedIntent.QUESTION,.82f)); if(analysis.hasRequest)add(LabelConfidence(DetectedIntent.HELP_REQUEST,.7f)); if(listOf("sorry","apolog").any(l::contains))add(LabelConfidence(DetectedIntent.APOLOGY,.88f)); if(listOf("thanks","thank you").any(l::contains))add(LabelConfidence(DetectedIntent.THANKS,.9f)); if(listOf("congrats","congratulations").any(l::contains))add(LabelConfidence(DetectedIntent.CONGRATULATIONS,.85f)); if(listOf("plan","meet","free on","schedule").any(l::contains))add(LabelConfidence(DetectedIntent.MAKING_PLANS,.68f)); if(listOf("miss you","cute","date").any(l::contains))add(LabelConfidence(DetectedIntent.FLIRTING,.55f)); if(listOf("sad","hurt","worried","rough").any(l::contains))add(LabelConfidence(DetectedIntent.EMOTIONAL_SUPPORT,.7f)); if(listOf("guess what","news","got a").any(l::contains))add(LabelConfidence(DetectedIntent.SHARING_NEWS,.6f)); if(analysis.hasGreeting)add(LabelConfidence(DetectedIntent.GREETING,.9f)); if(analysis.hasFarewell)add(LabelConfidence(DetectedIntent.FAREWELL,.85f)); if(isEmpty())add(LabelConfidence(DetectedIntent.CASUAL_CONVERSATION,.6f)) } } }
interface EmotionDetector { fun detect(message: String): LabelConfidence<DetectedEmotion> }
class HeuristicEmotionDetector : EmotionDetector { override fun detect(message:String):LabelConfidence<DetectedEmotion>{val l=message.lowercase(); return when { listOf("angry","mad","furious").any(l::contains)->LabelConfidence(DetectedEmotion.ANGRY,.72f); listOf("sad","cry","hurt").any(l::contains)->LabelConfidence(DetectedEmotion.SAD,.72f); listOf("worried","anxious","scared").any(l::contains)->LabelConfidence(DetectedEmotion.WORRIED,.7f); listOf("excited","can't wait","cant wait").any(l::contains)->LabelConfidence(DetectedEmotion.EXCITED,.78f); listOf("lol","haha","😂").any(l::contains)->LabelConfidence(DetectedEmotion.PLAYFUL,.7f); listOf("great","happy","love").any(l::contains)->LabelConfidence(DetectedEmotion.HAPPY,.65f); else->LabelConfidence(DetectedEmotion.NEUTRAL,.55f) } } }
class RelationshipAnalyzer { fun assess(memory: MemoryContext) = memory.relationshipContext?.takeIf { it.isNotBlank() }?.let { RelationshipAssessment(it, "Uses approved relationship-context memory.") } ?: RelationshipAssessment(null, "No approved relationship context is available.") }
class StrategySelector { fun select(intents: List<LabelConfidence<DetectedIntent>>, emotion: LabelConfidence<DetectedEmotion>, relationship: RelationshipAssessment): Pair<ConversationGoal, ResponseStrategy> { val labels=intents.map{it.label}; return when { DetectedIntent.EMOTIONAL_SUPPORT in labels || emotion.label in setOf(DetectedEmotion.SAD,DetectedEmotion.WORRIED)->ConversationGoal.COMFORT to ResponseStrategy.EMPATHETIC; DetectedIntent.QUESTION in labels || DetectedIntent.HELP_REQUEST in labels->ConversationGoal.ANSWER_QUESTION to ResponseStrategy.INFORMATIVE; DetectedIntent.MAKING_PLANS in labels->ConversationGoal.MAKE_PLANS to ResponseStrategy.CONVERSATIONAL; DetectedIntent.FAREWELL in labels->ConversationGoal.END_POLITELY to ResponseStrategy.CONVERSATIONAL; DetectedIntent.FLIRTING in labels && relationship.label != null->ConversationGoal.CONTINUE_CONVERSATION to ResponseStrategy.FLIRTY; else->ConversationGoal.CONTINUE_CONVERSATION to if(emotion.label==DetectedEmotion.PLAYFUL) ResponseStrategy.PLAYFUL else ResponseStrategy.CONVERSATIONAL } } }
